services:
  apache:
    image: php:8.1-apache 
    restart: always
    ports:
      - "16384:80"
    volumes:
      - ./site:/var/www/html
      - ./site/apache-config.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    build:
     context: .
     dockerfile: Dockerfile

  db:
    image: mysql:8.0 
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest 
    restart: always
    ports:
      - "16385:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db:
